# This is a generated file. Not intended for manual editing.
services:
  sweetnotes.api:
    build:
      context: "/Users/esausilva/Development/Projects/sweet-notes/SweetNotesApi"
      dockerfile: "src/Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "esausilva/sweetnotes.api:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "/Users/esausilva/.microsoft/usersecrets:/home/app/.microsoft/usersecrets"
    - "/Users/esausilva/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/esausilva/Development/Projects/sweet-notes/SweetNotesApi/src/Api:/app:rw"
    - "/Users/esausilva/Development/Projects/sweet-notes/SweetNotesApi:/src:rw"
    - "/Users/esausilva/.local/share/JetBrains/RiderRemoteDebugger/2023.3.3/Linux64:/opt/rider-debugger"
    - "/Applications/Rider.app/Contents/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/Users/esausilva/Library/Logs/JetBrains/Rider2023.3/DebuggerWorker/JetBrains.Debugger.Worker.2024_7_18_18_02_45:/var/opt/rider-debugger:rw"
    working_dir: "/app"
