services:
  
  sweetnotes.api:
    image: esausilva/sweetnotes.api:latest
    container_name: SweetNotes.Api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5068
      - ASPNETCORE_HTTP_PORTS=5068
      #- ASPNETCORE_URLS=http://+:5068;https://+:5069
      #- ASPNETCORE_HTTPS_PORTS=5069
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
      - ConnectionStrings:SweetNotes=Server=sweetnotes.db;Port=5432;Database=SweetNotes;User Id=esausilva;Password=12345
    ports:
      - "5068:5068"
    depends_on:
      - sweetnotes.db
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
        
  sweetnotes.db:
    image: postgres:latest
    container_name: SweetNotes.Db
    environment:
      - POSTGRES_USER=esausilva
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=SweetNotes
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"